image: bcksysrds/gitlab-ci-pipeline-for-laravel

stages:
  - build
  - test
  - deploy

.init_rsync: &init_rsync |
  echo ${RSYNC_SECRET} > /etc/rsync.secret
  chmod 600 /etc/rsync.secret

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path './node_modules/*' -exec chmod 664 {} \;
  find . -type d -not -path './node_modules/*' -exec chmod 775 {} \;

.change_file_owner: &change_file_owner |
  addgroup -S de_us -g 503 && adduser -S de_us -G de_us -u 503
  chown -R de_us.de_us ./

build-testing:
  stage: build
  cache:
    # key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      # - rm -rf node_modules
      # - rm package-lock.json
      - npm cache clean -f
      - npm install
      - npm run build:testing
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  only:
    - testing

build-staging:
  stage: build
  cache:
    # key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - npm cache clean -f
      - npm install
      - npm run build:staging
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  only:
    - staging

build-production:
  stage: build
  cache:
    # key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - npm cache clean -f
      - npm install
      - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  only:
    - master

deploy-testing:
  stage: deploy
  script:
    - *init_rsync
    - *change_file_permissions
    - *change_file_owner
    - rsync -av --delete --exclude=.git --password-file=/etc/rsync.secret --port=${RSYNC_PORT_TESTING} ./dist/ root@${RSYNC_HOST_TESTING}::${RSYNC_MODULE_TESTING}
  only:
    - testing

deploy-staging:
  stage: deploy
  script:
    - *init_rsync
    - *change_file_permissions
    - *change_file_owner
    - rsync -av --delete --exclude=.git --password-file=/etc/rsync.secret --port=${RSYNC_PORT_STAGING} ./dist/ root@${RSYNC_HOST_STAGING}::${RSYNC_MODULE_STAGING}
  only:
    - staging

deploy-production:
  stage: deploy
  script:
    - *init_rsync
    - *change_file_permissions
    - *change_file_owner
    - rsync -av --delete --exclude=.git --password-file=/etc/rsync.secret --port=${RSYNC_PORT_PRODUCTION} ./dist/ root@${RSYNC_HOST_PRODUCTION}::${RSYNC_MODULE_PRODUCTION}
  when: manual
  only:
    - master
